
# Local Putty Key C:/Users/danie/.ssh/id_geni_ssh_rsa.ppk
# Local Rsa Key: C:/Users/danie/.ssh/id_geni_ssh_rsa
# """

# ovs_port/eth1 ether 02:5c:8e:9e:f9:a4  client 10.10.1.16        
# ovs_port/eth2 ether 02:90:94:70:9e:19  client2 10.10.1.7        
# ovs_port/eth3 ether 02:34:61:eb:86:34  VM1 10.10.1.11           
# ovs_port/eth4 ether 02:59:35:b0:86:92  Attacker 10.10.1.15
# ovs_port/eth5 ether 02:0f:7b:4a:c1:13  VM3          10.10.1.13 
# ovs_port/eth6 ether 02:6a:e6:24:a0:bd  DummyVM    10.10.1.14
# ovs_port/eth7 ether 02:b9:cb:69:37:7e  VM2          10.10.1.12
# ovs_port/eth8 ether 02:b0:8b:e3:4b:27  Proxy        10.10.1.18
# """  




key_cred:
    putty_key: /users/daniel05/.ssh/id_geni_ssh_rsa.ppk #C:/Users/danie/.ssh/id_geni_ssh_rsa.ppk   This putty key needs to be in every VM      
    controller_rsa_ssh_key_path: /users/daniel05/.ssh/id_geni_ssh_rsa #C:/Users/danie/.ssh/id_geni_ssh_rsa  # C:/Users/danie/.ssh/id_geni_ssh_rsa 
    passphrase: 12345

vm_pool:  # List of vms to choose from
    - vm1
    - vm2
    - vm3

vms:
    vm1:
        host: pc5.geni.it.cornell.edu
        user: daniel05
        port: 25010
        ovs_port: 3             # ovs bridge port to vm
        local_ip: 10.10.1.1
    vm2: 
        user: daniel05
        host: pc1.geni.it.cornell.edu
        port: 25014
        ovs_port: 7
        local_ip: 10.10.1.2
    vm3:  #daniel05@pc3.geni.it.cornell.edu -p 25010
        user: daniel05
        host: pc3.geni.it.cornell.edu
        port: 25010
        ovs_port: 5
        local_ip: 10.10.1.3


Dummy_VM:
    user: daniel05
    host: pc2.instageni.rnet.missouri.edu
    port: 25610
    ovs_port: 6
    local_ip: 10.10.1.4

